import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {FC, PropsWithChildren} from "react";
import Navbar from "@/app/_components/Navbar";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({children}) => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar/>
                <main className="flex min-h-screen flex-col items-center justify-between p-24">
                    {children}
                </main>
            </body>
        </html>
    );
}

export default RootLayout;
